spring.application.name=glasgowuniversityrowingwebsite

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP Connection Pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# JWT secret key
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

# Supabase Bucket configuration
supabase.url=${SUPABASE_URL}
supabase.committee.bucket=${SUPABASE_COMMITTEE_BUCKET}
supabase.news.bucket=${SUPABASE_NEWS_BUCKET}
supabase.service.role.key=${SUPABASE_KEY}

# Mailchimp Configuration
mailchimp.api.key=${MAILCHIMP_API_KEY}
mailchimp.list.id=${MAILCHIMP_LIST_ID}
mailchimp.server.prefix=${MAILCHIMP_SERVER_PREFIX}

spring.config.import=optional:file:.env[.properties]